const mongoose = require('mongoose');



const UserSchema = new mongoose.Schema({
    rollno: Number,
    name: String,
    mothername: String,
    fathername: String,
    dob: Date,
    school: String,
    schoolId: String,
    subjectcode1: String,
    subjectname1: String,
    theory1: Number,
    practical1: Number,
    total1: Number,
    totalinwords1: String,
    positionalgrade1: String,
    subjectcode2: String,
    subjectname2: String,
    theory2: Number,
    practical2: Number,
    total2: Number,
    totalinwords2: String,
    positionalgrade2: String,
    subjectcode3: String,
    subjectname3: String,
    theory3: Number,
    practical3: Number,
    total3: Number,
    totalinwords3: String,
    positionalgrade3: String,
    subjectcode4: String,
    subjectname4: String,
    theory4: Number,
    practical4: Number,
    total4: Number,
    totalinwords4: String,
    positionalgrade4: String,
    subjectcode5: String,
    subjectname5: String,
    theory5: Number,
    practical5: Number,
    total5: Number,
    totalinwords5: String,
    positionalgrade5: String,
    subjectcode6: String,
    subjectname6: String,
    theory6: Number,
    practical6: Number,
    total6: Number,
    totalinwords6: String,
    positionalgrade6: String,
    result: String
});

const User = mongoose.model('User', UserSchema);
module.exports = { User };
